### ISSUE TITLE
Document dpr-api local installation and setup

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-docs#13]
Document installation process on local server. Follow again instructions from dpr-api/README.md, check and add what missing, document it.

[TODO]  _Not yet sure if it will be worth to copy the same info from dpr-api/README to the dpr-docs_

* Auth0 setup docs are in separate issue: #14 
* Amazon s3 setup docs are in separete issue: #15

**Comment by rufuspollock** [comment]
We are putting this on hold for now as not a priority.

**Comment by rufuspollock** [comment]
@Fak3 can you report on final status here - was this half-done, nearly-done, not done at all ...

**Comment by Fak3** [comment]
@rufuspollock I did not start to write anything, but I have checked and followed README in dpr-api. IIRC it worked for me, but I had some issues with launching tests: https://github.com/frictionlessdata/dpr-api/issues/208

**Comment by rufuspollock** [comment]
FIXED. Ok so i'm marking this as fixed.

@Fak3 did you anything on #14 and #15?
