### ISSUE TITLE
Document amazon s3 setup

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-docs#15]
Walk through setup again, check and document all that has to be done.

**Comment by rufuspollock** [comment]
@Fak3 this stuff should be automated in the deploy scripts - you don't have to document all of this. As per the epic you can mainly just point at existing READMEs (though if stuff is missing you can mention that).

**Comment by Fak3** [comment]
@rufuspollock Ok, for now I only adjusted existing S3 datastore docs.

Currently there is no README anywhere with the info on how to configure s3. And the deploy script currently does not automagically create aws users and buckets. So this docs will fill the gap for now.

**Comment by rufuspollock** [comment]
@Fak3 - if the deploy script does not create automagically create AWS buckets that is a bug - and we should file that item ;-)
