### ISSUE TITLE
Use travis to auto-build website (gh-pages) on push to master

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#20]
## Tasks

- [x] Create .travis.yml
- [x] Create script to build docs and push to Gh-branch

**Comment by rufuspollock** [comment]
@subhankarb what's the status here? Don't think it is working atm ...

**Comment by subhankarb** [comment]
FIXED.
Any update automatically reflects in https://frictionlessdata.github.io/dpr-docs/
