### ISSUE TITLE
[doc] Infrastructure setup

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-docs#4]
@subhankarb commented on [Thu Dec 22 2016](https://github.com/frictionlessdata/dpr-api/issues/163)

What infrastructure we need with what permissions and setup doc

## Tasks

- [ ] S3 and Lambda ... 
- [ ] Domain and SSL setup #10

**Comment by rufuspollock** [comment]
WONTFIX. Now obsolete.
