### ISSUE TITLE
Fix a sequence diagram on developers/publish page

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-docs#68]
The sequence diagram on http://docs.datahub.io/developers/publish/ is out of date at the moment. We want to update and improve it.

## Acceptance criteria

* [x] the diagram represents actual flow of the system

## Tasks

* [x] analysis on current system flow
* [x] implement analysis

**Comment by zelima** [comment]
FIXED diagrams look accurate enough at the moment
