### ISSUE TITLE
Update core data curators guide for datahub.io

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#72]
We want to update data curators guide in datahub.io/docs

## Acceptance criteria

* [ ] core data curators page updated

## Tasks

* [ ] update `views/docs_home` to link created pages

**Comment by Mikanebu** [comment]
Issue moved to [datahq/frontend #100](https://github.com/datahq/frontend/issues/100) via [**ZenHub**](https://www.zenhub.com/)
