### ISSUE TITLE
Terminology: api-key vs auth_token vs secret vs access_token

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-docs#8]
Currently we are using different names for that same thing in diffrernt places. We should decide how to call the permanent secret key.

* dpmpy config: access_token
* api docs: api-key
* dpr-api request parameter: secret
* dpr-api user model: secret
* dpr-api error: "Secret key", sometimes just "secret"
* dpr-frontend: "Your Secret Token"

**Comment by Fak3** [comment]
I like "Secret key" most of all variants.
* it does not create confusion with our temporary jwt tokens
* it suggests that the key should be kept secret

**Comment by rufuspollock** [comment]
@zelima assigning to you but feel free to reassign. I think this is a good moment to fix this as we are doing the cli workl

**Comment by rufuspollock** [comment]
FIXED. We are resolved on token or "(secret) auth token"
